update_limit: 5000
vocab_size: 20000
sent_type: "bi_rnn"
latent_size: 100
full_kl_step: 10000
dec_keep_prob: 1.0
cell_type: "gru"
embed_size: 300
cxt_cell_size: 600
sent_cell_size: 300
memory_cell_size: 300
dec_cell_size: 500
context_window: 2
step_size: 2
max_utt_len: 30
max_per_len: 15
max_per_line: 6
max_per_words: 15
num_layer: 1
hops: 3
use_copy: False
op: "adam"
grad_clip: 5.0
init_w: 0.08
batch_size: 32
init_lr: 0.001
lr_hold: 1
lr_decay: 0.6
keep_prob: 1.0
improve_threshold: 0.996
patient_increase: 1.0
early_stop: True
max_epoch: 50
grad_noise: 0.0
temperature: 0.1
test_samples: 5
perw_weight: 2.5
othw_weight: 0.15
balance_factor: 5.0
test_batchsize: 1